application: pyhackouts
version: 1
runtime: python
api_version: 1

default_expiration: "0m"

handlers:
- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)

- url: .*
  script: main.py
